# Get annotation and genome-context data for a subset of genomes for visualizing strict viral regions

In [205]:
! pip install polars --quiet

In [206]:
from pathlib import Path
OUTPUT_TABLES_DIR = Path("./tables/genome_viz")
OUTPUT_TABLES_DIR.mkdir(exist_ok=True, parents=True)

In [207]:
import os
os.environ["POLARS_MAX_THREADS"] = str(50)
import polars as pl
pl.Config.set_fmt_str_lengths(100)

polars.config.Config

## Load pre-split training data

In [208]:
all_data = (
    pl.read_parquet(
        "/storage2/scratch/kosmopoulos/projects/checkAMG/training_data/processing/genomad_progenomes_combined/training_data_pre_split.parquet"
    )
    .drop([
        "LGBM_viral_prob", "Viral_Origin_Confidence", # Old features used from a model fit on an older model in CheckAMG annotate, not the latest results
    ])
    .select([
        "Protein", "Contig",
        "region_label", "original_region_label", "region_contig_type",
        "True Positive", "True Negative",
        "Source", "Dataset"
    ])
)

In [209]:
all_data

shape: (16_825_809, 9)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ Protein    ┆ Contig     ┆ region_la ┆ original_ ┆ … ┆ True      ┆ True      ┆ Source ┆ Dataset   │
│ ---        ┆ ---        ┆ bel       ┆ region_la ┆   ┆ Positive  ┆ Negative  ┆ ---    ┆ ---       │
│ str        ┆ str        ┆ ---       ┆ bel       ┆   ┆ ---       ┆ ---       ┆ str    ┆ str       │
│            ┆            ┆ str       ┆ ---       ┆   ┆ bool      ┆ bool      ┆        ┆           │
│            ┆            ┆           ┆ str       ┆   ┆           ┆           ┆        ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ 1015567_co ┆ 1015567_co ┆ Viral     ┆ Viral     ┆ … ┆ true      ┆ false     ┆ Virus  ┆ geNomad   │
│ ntig_2210_ ┆ ntig_2210_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 74_1015567 ┆ 74_1015567 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ _contig_22 ┆ _contig_22 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 10|fragmen ┆ 10|fragmen ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ t_1_1      ┆ t_1        ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 1015567_co ┆ 1015567_co ┆ Viral     ┆ Viral     ┆ … ┆ true      ┆ false     ┆ Virus  ┆ geNomad   │
│ ntig_2210_ ┆ ntig_2210_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 74_1015567 ┆ 74_1015567 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ _contig_22 ┆ _contig_22 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 10|fragmen ┆ 10|fragmen ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ t_1_2      ┆ t_1        ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 1015567_co ┆ 1015567_co ┆ Viral     ┆ Viral     ┆ … ┆ true      ┆ false     ┆ Virus  ┆ geNomad   │
│ ntig_2210_ ┆ ntig_2210_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 74_1015567 ┆ 74_1015567 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ _contig_22 ┆ _contig_22 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 10|fragmen ┆ 10|fragmen ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ t_1_3      ┆ t_1        ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 1015567_co ┆ 1015567_co ┆ Viral     ┆ Viral     ┆ … ┆ true      ┆ false     ┆ Virus  ┆ geNomad   │
│ ntig_2210_ ┆ ntig_2210_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 74_1015567 ┆ 74_1015567 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ _contig_22 ┆ _contig_22 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 10|fragmen ┆ 10|fragmen ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ t_1_4      ┆ t_1        ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 1015567_co ┆ 1015567_co ┆ Viral     ┆ Viral     ┆ … ┆ true      ┆ false     ┆ Virus  ┆ geNomad   │
│ ntig_2210_ ┆ ntig_2210_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 74_1015567 ┆ 74_1015567 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ _contig_22 ┆ _contig_22 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 10|fragmen ┆ 10|fragmen ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ t_1_5      ┆ t_1        ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …      ┆ …         │
│ 999547.SAM ┆ 999547.SAM ┆ Nonviral  ┆ Nonviral  ┆ … ┆ false     ┆ true      ┆ MGE    ┆ progenome │
│ N02440716. ┆ N02440716. ┆           ┆           ┆   ┆           ┆           ┆        ┆ s         │
│ KI421503~1 ┆ KI421503~1 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ -174096~ch ┆ -174096~ch ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ romosome_m ┆ romosome_m ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ ixed_172   ┆ ixed       ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 999547.SAM ┆ 999547.SAM ┆ Nonviral  ┆ Nonviral  ┆ … ┆ false     ┆ true      ┆ MGE    ┆ progenome │
│ N02440716. ┆ N02440716. ┆           ┆           ┆   ┆           ┆           ┆        ┆ s         │
│ KI421503~1 ┆ KI421503~1 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ -174096~ch ┆ -174096~ch ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ romosome_m ┆ romosome_m ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ ixed_173   ┆ ixed       ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 999547.SAM ┆ 999547.SAM ┆ Nonviral  ┆ Nonviral  ┆ … ┆ false     ┆ true      ┆ MGE    ┆ progenome │
│ N02440716. ┆ N02440716. ┆           ┆           ┆   ┆           ┆           ┆        ┆ s         │
│ KI421503~1 ┆ KI421503~1 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ -174096~ch ┆ -174096~ch ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ romosome_m ┆ romosome_m ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ ixed_174   ┆ ixed       ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 999547.SAM ┆ 999547.SAM ┆ Nonviral  ┆ Nonviral  ┆ … ┆ false     ┆ true      ┆ Host   ┆ progenome │
│ N02440716. ┆ N02440716. ┆           ┆           ┆   ┆           ┆           ┆        ┆ s         │
│ KI421503~1 ┆ KI421503~1 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ -174096~ch ┆ -174096~ch ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ romosome_m ┆ romosome_m ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ ixed_175   ┆ ixed       ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 999547.SAM ┆ 999547.SAM ┆ Nonviral  ┆ Nonviral  ┆ … ┆ false     ┆ true      ┆ Host   ┆ progenome │
│ N02440716. ┆ N02440716. ┆           ┆           ┆   ┆           ┆           ┆        ┆ s         │
│ KI421503~1 ┆ KI421503~1 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ -174096~ch ┆ -174096~ch ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ romosome_m ┆ romosome_m ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ ixed_176   ┆ ixed       ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

## Load genome context and annotations from CheckAMG results

Only load proteins encoded on contigs that have at least one protein that matches to every "step" in the strict/ambiguous viral region algorithm.

In [210]:
CHECKAMG_OUTPUT_DIR = Path("/storage2/scratch/kosmopoulos/projects/checkAMG/training_data/processing/checkamg_annotate_outputs_1.1")
CHECKAMG_GENOMAD_DIR = CHECKAMG_OUTPUT_DIR.joinpath("checkamg_annotate_genomad_dataset")
CHECKAMG_PROGENOMES_DIR = CHECKAMG_OUTPUT_DIR.joinpath("checkamg_annotate_progenomes_dataset")

In [211]:
checkamg_context_schema = pl.read_parquet_schema(CHECKAMG_GENOMAD_DIR.joinpath("results/genes_genomic_context.parquet"))
checkamg_context_schema

{'genome': String,
 'contig': String,
 'protein': String,
 'gene_number': Int64,
 'contig_pos_start': Int64,
 'contig_pos_end': Int64,
 'frame': Int64,
 'is_bin': String,
 'dbCAN_score': Float64,
 'Pfam_score': Float64,
 'METABOLIC_score': Float64,
 'KEGG_score': Float64,
 'CAMPER_score': Float64,
 'PHROG_score': Float64,
 'FOAM_score': Float64,
 'dbCAN_alignment_type': String,
 'Pfam_alignment_type': String,
 'METABOLIC_alignment_type': String,
 'KEGG_alignment_type': String,
 'CAMPER_alignment_type': String,
 'PHROG_alignment_type': String,
 'FOAM_alignment_type': String,
 'dbCAN_hmm_id': String,
 'Pfam_hmm_id': String,
 'METABOLIC_hmm_id': String,
 'KEGG_hmm_id': String,
 'CAMPER_hmm_id': String,
 'PHROG_hmm_id': String,
 'FOAM_hmm_id': String,
 'dbCAN_evalue': Float64,
 'Pfam_evalue': Float64,
 'METABOLIC_evalue': Float64,
 'KEGG_evalue': Float64,
 'CAMPER_evalue': Float64,
 'PHROG_evalue': Float64,
 'FOAM_evalue': Float64,
 'dbCAN_coverage_sequence': Float64,
 'Pfam_coverage_sequence': Float64,
 'METABOLIC_coverage_sequence': Float64,
 'KEGG_coverage_sequence': Float64,
 'CAMPER_coverage_sequence': Float64,
 'PHROG_coverage_sequence': Float64,
 'FOAM_coverage_sequence': Float64,
 'dbCAN_coverage_hmm': Float64,
 'Pfam_coverage_hmm': Float64,
 'METABOLIC_coverage_hmm': Float64,
 'KEGG_coverage_hmm': Float64,
 'CAMPER_coverage_hmm': Float64,
 'PHROG_coverage_hmm': Float64,
 'FOAM_coverage_hmm': Float64,
 'Pfam_V-score': Float64,
 'Pfam_VL-score': Float64,
 'KEGG_V-score': Float64,
 'KEGG_VL-score': Float64,
 'PHROG_V-score': Float64,
 'PHROG_VL-score': Float64,
 'gene_length_bases': Int64,
 'prot_length_AAs': Int32,
 'contig_left_end_dist': Float32,
 'contig_right_end_dist': Float32,
 'contig_left_end_gene_dist': Float32,
 'contig_right_end_gene_dist': Float32,
 'contig_avg_KEGG_V-score': Float64,
 'contig_avg_Pfam_V-score': Float64,
 'contig_avg_PHROG_V-score': Float64,
 'contig_avg_KEGG_VL-score': Float64,
 'contig_avg_Pfam_VL-score': Float64,
 'contig_avg_PHROG_VL-score': Float64,
 'circular_contig': Boolean,
 'window_avg_KEGG_VL-score': Float64,
 'window_avg_Pfam_VL-score': Float64,
 'window_avg_PHROG_VL-score': Float64,
 'window_avg_KEGG_V-score': Float64,
 'window_avg_Pfam_V-score': Float64,
 'window_avg_PHROG_V-score': Float64,
 'candidate_region_id': Int32,
 'refined_region_id': Int32,
 'viral_region_id': Int32,
 'step1_seed_strict_wvl': Boolean,
 'step1_in_candidate_region': Boolean,
 'step2_passes_vscore_gate': Boolean,
 'step2_in_refined_core': Boolean,
 'step3_bridge_ok': Boolean,
 'step3_in_walkback_extended': Boolean,
 'step4_in_snapped_region': Boolean,
 'step5_in_merged_region': Boolean,
 'KEGG_viral_left_dist': Float32,
 'KEGG_viral_right_dist': Float32,
 'Pfam_viral_left_dist': Float32,
 'Pfam_viral_right_dist': Float32,
 'PHROG_viral_left_dist': Float32,
 'PHROG_viral_right_dist': Float32,
 'KEGG_MGE_left_dist': Float32,
 'KEGG_MGE_right_dist': Float32,
 'Pfam_MGE_left_dist': Float32,
 'Pfam_MGE_right_dist': Float32,
 'PHROG_MGE_left_dist': Float32,
 'PHROG_MGE_right_dist': Float32,
 'KEGG_V-score_left_MGE': Float32,
 'KEGG_V-score_right_MGE': Float32,
 'KEGG_VL-score_left_MGE': Float32,
 'KEGG_VL-score_right_MGE': Float32,
 'Pfam_V-score_left_MGE': Float32,
 'Pfam_V-score_right_MGE': Float32,
 'Pfam_VL-score_left_MGE': Float32,
 'Pfam_VL-score_right_MGE': Float32,
 'PHROG_V-score_left_MGE': Float32,
 'PHROG_V-score_right_MGE': Float32,
 'PHROG_VL-score_left_MGE': Float32,
 'PHROG_VL-score_right_MGE': Float32,
 'LGBM_viral_prob': Float32,
 'Viral_Origin_Confidence': String}

In [212]:
required_cols_context = [
    "protein", "contig",
    "gene_number", "contig_pos_start", "contig_pos_end", "frame",
    "KEGG_V-score", "Pfam_V-score", "PHROG_V-score",
    "window_avg_KEGG_VL-score", "window_avg_Pfam_VL-score", "window_avg_PHROG_VL-score",
] + [col for col in checkamg_context_schema.keys() if col.startswith("step")] + ["viral_region_id"]
required_cols_context

['protein',
 'contig',
 'gene_number',
 'contig_pos_start',
 'contig_pos_end',
 'frame',
 'KEGG_V-score',
 'Pfam_V-score',
 'PHROG_V-score',
 'window_avg_KEGG_VL-score',
 'window_avg_Pfam_VL-score',
 'window_avg_PHROG_VL-score',
 'step1_seed_strict_wvl',
 'step1_in_candidate_region',
 'step2_passes_vscore_gate',
 'step2_in_refined_core',
 'step3_bridge_ok',
 'step3_in_walkback_extended',
 'step4_in_snapped_region',
 'step5_in_merged_region',
 'viral_region_id']

In [216]:
checkamg_context = (
    pl.concat([
        pl.scan_parquet(
            CHECKAMG_GENOMAD_DIR.joinpath("results/genes_genomic_context.parquet")
        )
        .select(required_cols_context),
        pl.scan_parquet(
            CHECKAMG_PROGENOMES_DIR.joinpath("results/genes_genomic_context.parquet"),
        )
        .select(required_cols_context),
    ])
    .collect()
)

In [217]:
checkamg_context

shape: (16_825_809, 21)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ protein   ┆ contig    ┆ gene_numb ┆ contig_po ┆ … ┆ step3_in_ ┆ step4_in_ ┆ step5_in_ ┆ viral_re │
│ ---       ┆ ---       ┆ er        ┆ s_start   ┆   ┆ walkback_ ┆ snapped_r ┆ merged_re ┆ gion_id  │
│ str       ┆ str       ┆ ---       ┆ ---       ┆   ┆ extended  ┆ egion     ┆ gion      ┆ ---      │
│           ┆           ┆ i64       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ i32      │
│           ┆           ┆           ┆           ┆   ┆ bool      ┆ bool      ┆ bool      ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 1015567_c ┆ 1015567_c ┆ 1         ┆ 36        ┆ … ┆ false     ┆ false     ┆ false     ┆ null     │
│ ontig_221 ┆ ontig_221 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0_74_1015 ┆ 0_74_1015 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 567_conti ┆ 567_conti ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ g_2210|fr ┆ g_2210|fr ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ agment_1_ ┆ agment_1  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1015567_c ┆ 1015567_c ┆ 2         ┆ 194       ┆ … ┆ true      ┆ true      ┆ false     ┆ null     │
│ ontig_221 ┆ ontig_221 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0_74_1015 ┆ 0_74_1015 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 567_conti ┆ 567_conti ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ g_2210|fr ┆ g_2210|fr ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ agment_1_ ┆ agment_1  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1015567_c ┆ 1015567_c ┆ 3         ┆ 520       ┆ … ┆ true      ┆ true      ┆ false     ┆ null     │
│ ontig_221 ┆ ontig_221 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0_74_1015 ┆ 0_74_1015 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 567_conti ┆ 567_conti ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ g_2210|fr ┆ g_2210|fr ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ agment_1_ ┆ agment_1  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1015567_c ┆ 1015567_c ┆ 4         ┆ 2154      ┆ … ┆ true      ┆ true      ┆ false     ┆ null     │
│ ontig_221 ┆ ontig_221 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0_74_1015 ┆ 0_74_1015 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 567_conti ┆ 567_conti ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ g_2210|fr ┆ g_2210|fr ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ agment_1_ ┆ agment_1  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 4         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1015567_c ┆ 1015567_c ┆ 5         ┆ 2426      ┆ … ┆ false     ┆ false     ┆ false     ┆ null     │
│ ontig_221 ┆ ontig_221 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 0_74_1015 ┆ 0_74_1015 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 567_conti ┆ 567_conti ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ g_2210|fr ┆ g_2210|fr ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ agment_1_ ┆ agment_1  ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 5         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 999547.SA ┆ 999547.SA ┆ 172       ┆ 169132    ┆ … ┆ true      ┆ true      ┆ true      ┆ 2        │
│ MN0244071 ┆ MN0244071 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6.KI42150 ┆ 6.KI42150 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3~1-17409 ┆ 3~1-17409 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6~chromos ┆ 6~chromos ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ome_mixed ┆ ome_mixed ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _172      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999547.SA ┆ 999547.SA ┆ 173       ┆ 170254    ┆ … ┆ true      ┆ true      ┆ true      ┆ 2        │
│ MN0244071 ┆ MN0244071 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6.KI42150 ┆ 6.KI42150 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3~1-17409 ┆ 3~1-17409 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6~chromos ┆ 6~chromos ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ome_mixed ┆ ome_mixed ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _173      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999547.SA ┆ 999547.SA ┆ 174       ┆ 171695    ┆ … ┆ true      ┆ true      ┆ true      ┆ 2        │
│ MN0244071 ┆ MN0244071 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6.KI42150 ┆ 6.KI42150 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3~1-17409 ┆ 3~1-17409 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6~chromos ┆ 6~chromos ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ome_mixed ┆ ome_mixed ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _174      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999547.SA ┆ 999547.SA ┆ 175       ┆ 172690    ┆ … ┆ true      ┆ true      ┆ true      ┆ 2        │
│ MN0244071 ┆ MN0244071 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6.KI42150 ┆ 6.KI42150 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3~1-17409 ┆ 3~1-17409 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6~chromos ┆ 6~chromos ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ome_mixed ┆ ome_mixed ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _175      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 999547.SA ┆ 999547.SA ┆ 176       ┆ 172794    ┆ … ┆ true      ┆ true      ┆ true      ┆ 2        │
│ MN0244071 ┆ MN0244071 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6.KI42150 ┆ 6.KI42150 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 3~1-17409 ┆ 3~1-17409 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6~chromos ┆ 6~chromos ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ome_mixed ┆ ome_mixed ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ _176      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [219]:
checkamg_annot_schema = pl.read_parquet_schema(CHECKAMG_GENOMAD_DIR.joinpath("results/gene_annotations.parquet"))
checkamg_annot_schema

{'Protein': String,
 'Contig': String,
 'Genome': String,
 'Function': String,
 'KEGG_hmm_id': String,
 'FOAM_hmm_id': String,
 'Pfam_hmm_id': String,
 'dbCAN_hmm_id': String,
 'METABOLIC_hmm_id': String,
 'CAMPER_hmm_id': String,
 'PHROG_hmm_id': String,
 'KEGG_score': Float64,
 'FOAM_score': Float64,
 'Pfam_score': Float64,
 'dbCAN_score': Float64,
 'METABOLIC_score': Float64,
 'CAMPER_score': Float64,
 'PHROG_score': Float64,
 'KEGG_coverage': Float64,
 'FOAM_coverage': Float64,
 'Pfam_coverage': Float64,
 'dbCAN_coverage': Float64,
 'METABOLIC_coverage': Float64,
 'CAMPER_coverage': Float64,
 'PHROG_coverage': Float64,
 'KEGG_V-score': Float64,
 'Pfam_V-score': Float64,
 'PHROG_V-score': Float64,
 'Viral_Flanking_Genes_Left_Dist': Float32,
 'Viral_Flanking_Genes_Right_Dist': Float32,
 'MGE_Flanking_Genes_Left_Dist': Float32,
 'MGE_Flanking_Genes_Right_Dist': Float32,
 'step5_in_merged_region': Boolean,
 'nonviral_region_pos': String,
 'Viral_Origin_Confidence': String,
 'KEGG_Description': String,
 'FOAM_Description': String,
 'Pfam_Description': String,
 'dbCAN_Description': String,
 'METABOLIC_Description': String,
 'CAMPER_Description': String,
 'PHROG_Description': String,
 'top_hit_hmm_id': String,
 'top_hit_description': String,
 'top_hit_db': String,
 'protein_in_ambig_region': Boolean}

In [220]:
ignore_annots = ["METABOLIC", "CAMPER", "dbCAN", "top_hit"] # Ignore some annotations to save space
required_cols_annots = [
    "Protein", "Contig", "Function",
] + [col for col in checkamg_annot_schema.keys() if (col.endswith("_hmm_id") or col.lower().endswith("_description")) and not any(annot in col for annot in ignore_annots)]
required_cols_annots

['Protein',
 'Contig',
 'Function',
 'KEGG_hmm_id',
 'FOAM_hmm_id',
 'Pfam_hmm_id',
 'PHROG_hmm_id',
 'KEGG_Description',
 'FOAM_Description',
 'Pfam_Description',
 'PHROG_Description']

In [221]:
valid_proteins = (
    checkamg_context
    .select(pl.col("protein").alias("Protein"))
    .unique()
).lazy()

checkamg_annots = (
    pl.concat([
        pl.scan_parquet(
            CHECKAMG_GENOMAD_DIR.joinpath("results/gene_annotations.parquet")
        )
        .select(required_cols_annots),
        pl.scan_parquet(
            CHECKAMG_PROGENOMES_DIR.joinpath("results/gene_annotations.parquet"),
        )
        .select(required_cols_annots),
    ])
    .join(valid_proteins, on="Protein", how="inner")
    .collect()
)

In [222]:
checkamg_annots

shape: (16_825_809, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Protein   ┆ Contig    ┆ Function  ┆ KEGG_hmm_ ┆ … ┆ KEGG_Desc ┆ FOAM_Desc ┆ Pfam_Desc ┆ PHROG_De │
│ ---       ┆ ---       ┆ ---       ┆ id        ┆   ┆ ription   ┆ ription   ┆ ription   ┆ scriptio │
│ str       ┆ str       ┆ str       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ n        │
│           ┆           ┆           ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ New_nucc_ ┆ New_nucc_ ┆ Viral RNA ┆ null      ┆ … ┆ null      ┆ null      ┆ Viral RNA ┆ null     │
│ id_383348 ┆ id_383348 ┆ -dependen ┆           ┆   ┆           ┆           ┆ -dependen ┆          │
│ |fragment ┆ |fragment ┆ t RNA pol ┆           ┆   ┆           ┆           ┆ t RNA pol ┆          │
│ _1_2      ┆ _1        ┆ ymerase   ┆           ┆   ┆           ┆           ┆ ymerase   ┆          │
│ 255451.SA ┆ 255451.SA ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ MN0389167 ┆ MN0389167 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 6.LHVJ010 ┆ 6.LHVJ010 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 00015~1-6 ┆ 00015~1-6 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 43952~chr ┆ 43952~chr ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ omosome_m ┆ omosome_m ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ ixed_313  ┆ ixed      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1765722.S ┆ 1765722.S ┆ pcaH; pro ┆ K00449    ┆ … ┆ pcaH; pro ┆ pcaG; pro ┆ Dioxygena ┆ null     │
│ AMN043045 ┆ AMN043045 ┆ tocatechu ┆           ┆   ┆ tocatechu ┆ tocatechu ┆ se        ┆          │
│ 58.LOCL01 ┆ 58.LOCL01 ┆ ate 3,4-d ┆           ┆   ┆ ate 3,4-d ┆ ate 3,4-d ┆           ┆          │
│ 000058~1- ┆ 000058~1- ┆ ioxygenas ┆           ┆   ┆ ioxygenas ┆ ioxygenas ┆           ┆          │
│ 205869~ch ┆ 205869~ch ┆ e, beta   ┆           ┆   ┆ e, beta   ┆ e, alpha  ┆           ┆          │
│ romosome_ ┆ romosome_ ┆ subunit   ┆           ┆   ┆ subunit   ┆ subunit   ┆           ┆          │
│ mixed_80  ┆ mixed     ┆ [EC:1.13. ┆           ┆   ┆ [EC:1.13. ┆ [EC:1.13. ┆           ┆          │
│           ┆           ┆ 11.3]     ┆           ┆   ┆ 11.3]     ┆ 11.3];    ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ pcaH; pro ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ tocatechu ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ate 3,4-d ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ ioxy…     ┆           ┆          │
│ 269798.SA ┆ 269798.SA ┆ asbA; spe ┆ K24108    ┆ … ┆ asbA; spe ┆ null      ┆ null      ┆ null     │
│ MN0259853 ┆ MN0259853 ┆ rmidine-c ┆           ┆   ┆ rmidine-c ┆           ┆           ┆          │
│ 6.CP00038 ┆ 6.CP00038 ┆ itrate    ┆           ┆   ┆ itrate    ┆           ┆           ┆          │
│ 3~1-44332 ┆ 3~1-44332 ┆ ligase    ┆           ┆   ┆ ligase    ┆           ┆           ┆          │
│ 18~chromo ┆ 18~chromo ┆ [EC:6.3.2 ┆           ┆   ┆ [EC:6.3.2 ┆           ┆           ┆          │
│ some_mixe ┆ some_mixe ┆ .-]       ┆           ┆   ┆ .-]       ┆           ┆           ┆          │
│ d_576     ┆ d         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ PLXQ01000 ┆ PLXQ01000 ┆ serB-plsC ┆ K15781    ┆ … ┆ serB-plsC ┆ serB,     ┆ haloacid  ┆ null     │
│ 071.1|fra ┆ 071.1|fra ┆ ;         ┆           ┆   ┆ ;         ┆ PSPH; pho ┆ dehalogen ┆          │
│ gment_2_3 ┆ gment_2   ┆ putative  ┆           ┆   ┆ putative  ┆ sphoserin ┆ ase-like  ┆          │
│           ┆           ┆ phosphose ┆           ┆   ┆ phosphose ┆ e phospha ┆ hydrolase ┆          │
│           ┆           ┆ rine phos ┆           ┆   ┆ rine phos ┆ tase [EC: ┆           ┆          │
│           ┆           ┆ phatase / ┆           ┆   ┆ phatase / ┆ 3.1.3.3]  ┆           ┆          │
│           ┆           ┆ 1-acylgly ┆           ┆   ┆ 1-acylgly ┆           ┆           ┆          │
│           ┆           ┆ cerol-3-p ┆           ┆   ┆ cerol-3-p ┆           ┆           ┆          │
│           ┆           ┆ hosphate  ┆           ┆   ┆ hosphate  ┆           ┆           ┆          │
│           ┆           ┆ O-acyltra ┆           ┆   ┆ O-acyltra ┆           ┆           ┆          │
│           ┆           ┆ nsferase  ┆           ┆   ┆ nsferase  ┆           ┆           ┆          │
│           ┆           ┆ [EC:3.1…  ┆           ┆   ┆ [EC:3.1…  ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ MICJ01000 ┆ MICJ01000 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 018.1|fra ┆ 018.1|fra ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ gment_1_3 ┆ gment_1   ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ fragment_ ┆ fragment_ ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ 17879_11  ┆ 17879     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1761744.S ┆ 1761744.S ┆ K07018;   ┆ K07018    ┆ … ┆ K07018;   ┆ null      ┆ null      ┆ null     │
│ AMN044879 ┆ AMN044879 ┆ uncharact ┆           ┆   ┆ uncharact ┆           ┆           ┆          │
│ 12.FNNR01 ┆ 12.FNNR01 ┆ erized    ┆           ┆   ┆ erized    ┆           ┆           ┆          │
│ 000002~1- ┆ 000002~1- ┆ protein   ┆           ┆   ┆ protein   ┆           ┆           ┆          │
│ 639715~ch ┆ 639715~ch ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ romosome_ ┆ romosome_ ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mixed_467 ┆ mixed     ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 426355.SA ┆ 426355.SA ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ MN0000027 ┆ MN0000027 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 7.CP00100 ┆ 7.CP00100 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 1~1-60778 ┆ 1~1-60778 ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 33~chromo ┆ 33~chromo ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ some_mixe ┆ some_mixe ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ d_981     ┆ d         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 758793.SA ┆ 758793.SA ┆ xoxF; lan ┆ K23995    ┆ … ┆ xoxF; lan ┆ mdh1,     ┆ Glucose/e ┆ null     │
│ MD0001285 ┆ MD0001285 ┆ thanide-d ┆           ┆   ┆ thanide-d ┆ mxaF;     ┆ thanol/al ┆          │
│ 4.AP01305 ┆ 4.AP01305 ┆ ependent  ┆           ┆   ┆ ependent  ┆ methanol  ┆ cohol deh ┆          │
│ 9~1-14653 ┆ 9~1-14653 ┆ methanol  ┆           ┆   ┆ methanol  ┆ dehydroge ┆ ydrogenas ┆          │
│ 56~chromo ┆ 56~chromo ┆ dehydroge ┆           ┆   ┆ dehydroge ┆ nase (cyt ┆ e, beta-p ┆          │
│ some_mixe ┆ some_mixe ┆ nase [EC: ┆           ┆   ┆ nase [EC: ┆ ochrome   ┆ ropeller  ┆          │
│ d_157     ┆ d         ┆ 1.1.2.10] ┆           ┆   ┆ 1.1.2.10] ┆ c)        ┆ domain    ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ subunit 1 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ [EC:1.1.2 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ .7]       ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Combine into one feature table and one sequence table for plotting

Random subsample contigs by 15%, but keep all contigs that had relabelled proteins (those are rarer) to reduce filesize, don't need them all anyway. Mark contigs that had proteins from progenomes re-labeled from Viral to Nonviral using the strict algorithm.

In [277]:
feature_table = (
    checkamg_context
    .join(
        checkamg_annots,
        left_on=["protein", "contig"],
        right_on=["Protein", "Contig"],
        how="inner"
    )
    .join(
        all_data,
        left_on=["protein", "contig"],
        right_on=["Protein", "Contig"],
        how="inner"
    )
    .sort(["Dataset", "contig", "contig_pos_start", "contig_pos_end"])
    .with_columns([
        pl.selectors.integer()
        .exclude(["frame", "gene_number"])
        .cast(pl.Int32),
        pl.col("frame").cast(pl.Int16),
        pl.col("gene_number").cast(pl.Int16),
        pl.selectors.float().cast(pl.Float32),
    ])
)

In [278]:
import random
random.seed(20260501)

genomad_contigs = (
    feature_table
    .filter(pl.col("Dataset") == "geNomad")
    .get_column("contig")
    .unique()
    .sort()
    .to_list()
)
progenomes_contigs = (
    feature_table
    .filter(pl.col("Dataset") == "progenomes")
    .get_column("contig")
    .unique()
    .sort()
    .to_list()
)

relabeled_contigs = (
    feature_table
    .filter(pl.col("region_label")!=pl.col("original_region_label"))
    .get_column("contig")
    .unique()
    .sort()
    .to_list()
)

sampled_contigs = sorted(list(set(
    random.sample(genomad_contigs, round(len(genomad_contigs) * 0.15)) +
    random.sample(progenomes_contigs, round(len(progenomes_contigs) * 0.15)) +
    relabeled_contigs
)))

In [279]:
sampled_contigs[:5], sampled_contigs[-5:], len(sampled_contigs)

(['1000562.SAMN03114893.JSAP01000059~167-104902~standalone_virus',
  '1000565.SAMN02471991.AFHG01000029~267036-303673~standalone_virus',
  '1000565.SAMN02471991.AFHG01000030~143724-146792~standalone_mge',
  '1000565.SAMN02471991.AFHG01000043~80-2316~standalone_mge',
  '1000565.SAMN02471991.AFHG01000044~40759-134788~standalone_virus'],
 ['fragment_9987',
  'fragment_9989',
  'fragment_999',
  'fragment_9992',
  'fragment_9999'],
 226631)

In [280]:
feature_table = feature_table.filter(pl.col("contig").is_in(sampled_contigs))
feature_table

shape: (3_906_089, 37)
┌────────────┬────────────┬───────────┬───────────┬───┬───────────┬───────────┬────────┬───────────┐
│ protein    ┆ contig     ┆ gene_numb ┆ contig_po ┆ … ┆ True      ┆ True      ┆ Source ┆ Dataset   │
│ ---        ┆ ---        ┆ er        ┆ s_start   ┆   ┆ Positive  ┆ Negative  ┆ ---    ┆ ---       │
│ str        ┆ str        ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ str    ┆ str       │
│            ┆            ┆ i16       ┆ i32       ┆   ┆ bool      ┆ bool      ┆        ┆           │
╞════════════╪════════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪════════╪═══════════╡
│ 1039479_co ┆ 1039479_co ┆ 1         ┆ 1         ┆ … ┆ true      ┆ false     ┆ Virus  ┆ geNomad   │
│ ntig_5232_ ┆ ntig_5232_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 3_1039479_ ┆ 3_1039479_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ contig_523 ┆ contig_523 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 2|fragment ┆ 2|fragment ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ _1_1       ┆ _1         ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 1039479_co ┆ 1039479_co ┆ 2         ┆ 606       ┆ … ┆ true      ┆ false     ┆ Virus  ┆ geNomad   │
│ ntig_5232_ ┆ ntig_5232_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 3_1039479_ ┆ 3_1039479_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ contig_523 ┆ contig_523 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 2|fragment ┆ 2|fragment ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ _1_2       ┆ _1         ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 1039479_co ┆ 1039479_co ┆ 3         ┆ 899       ┆ … ┆ true      ┆ false     ┆ Virus  ┆ geNomad   │
│ ntig_5232_ ┆ ntig_5232_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 3_1039479_ ┆ 3_1039479_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ contig_523 ┆ contig_523 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 2|fragment ┆ 2|fragment ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ _1_3       ┆ _1         ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 1039479_co ┆ 1039479_co ┆ 4         ┆ 1583      ┆ … ┆ true      ┆ false     ┆ Virus  ┆ geNomad   │
│ ntig_5232_ ┆ ntig_5232_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 3_1039479_ ┆ 3_1039479_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ contig_523 ┆ contig_523 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 2|fragment ┆ 2|fragment ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ _1_4       ┆ _1         ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 1039479_co ┆ 1039479_co ┆ 5         ┆ 1977      ┆ … ┆ true      ┆ false     ┆ Virus  ┆ geNomad   │
│ ntig_5232_ ┆ ntig_5232_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 3_1039479_ ┆ 3_1039479_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ contig_523 ┆ contig_523 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 2|fragment ┆ 2|fragment ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ _1_5       ┆ _1         ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ …          ┆ …          ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …      ┆ …         │
│ 999547.SAM ┆ 999547.SAM ┆ 3735      ┆ 3979276   ┆ … ┆ false     ┆ true      ┆ Host   ┆ progenome │
│ N02440716. ┆ N02440716. ┆           ┆           ┆   ┆           ┆           ┆        ┆ s         │
│ KI421500~1 ┆ KI421500~1 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ -3984464~c ┆ -3984464~c ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ hromosome_ ┆ hromosome_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ mixed_3735 ┆ mixed      ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 999547.SAM ┆ 999547.SAM ┆ 3736      ┆ 3980710   ┆ … ┆ false     ┆ true      ┆ Host   ┆ progenome │
│ N02440716. ┆ N02440716. ┆           ┆           ┆   ┆           ┆           ┆        ┆ s         │
│ KI421500~1 ┆ KI421500~1 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ -3984464~c ┆ -3984464~c ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ hromosome_ ┆ hromosome_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ mixed_3736 ┆ mixed      ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 999547.SAM ┆ 999547.SAM ┆ 3737      ┆ 3981091   ┆ … ┆ false     ┆ true      ┆ Host   ┆ progenome │
│ N02440716. ┆ N02440716. ┆           ┆           ┆   ┆           ┆           ┆        ┆ s         │
│ KI421500~1 ┆ KI421500~1 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ -3984464~c ┆ -3984464~c ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ hromosome_ ┆ hromosome_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ mixed_3737 ┆ mixed      ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 999547.SAM ┆ 999547.SAM ┆ 3738      ┆ 3982326   ┆ … ┆ false     ┆ true      ┆ Host   ┆ progenome │
│ N02440716. ┆ N02440716. ┆           ┆           ┆   ┆           ┆           ┆        ┆ s         │
│ KI421500~1 ┆ KI421500~1 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ -3984464~c ┆ -3984464~c ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ hromosome_ ┆ hromosome_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ mixed_3738 ┆ mixed      ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ 999547.SAM ┆ 999547.SAM ┆ 3739      ┆ 3983798   ┆ … ┆ false     ┆ true      ┆ Host   ┆ progenome │
│ N02440716. ┆ N02440716. ┆           ┆           ┆   ┆           ┆           ┆        ┆ s         │
│ KI421500~1 ┆ KI421500~1 ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ -3984464~c ┆ -3984464~c ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ hromosome_ ┆ hromosome_ ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
│ mixed_3739 ┆ mixed      ┆           ┆           ┆   ┆           ┆           ┆        ┆           │
└────────────┴────────────┴───────────┴───────────┴───┴───────────┴───────────┴────────┴───────────┘

In [281]:
feature_table.write_parquet(OUTPUT_TABLES_DIR.joinpath("genes_feature_table.parquet"))

In [285]:
sequence_table = (
    feature_table
    .with_columns([
        (pl.col("region_label") != pl.col("original_region_label")).alias("_relabeled"),
        pl.col("viral_region_id").is_not_null().alias("_in_strict_viral_region"),
    ])
    .group_by(["contig", "Dataset", "region_contig_type"])
    .agg([
        pl.col("contig_pos_end").max().cast(pl.Int32).alias("length"),
        pl.col("viral_region_id").n_unique().cast(pl.Int32).alias("n_viral_regions"),
        pl.len().cast(pl.Int32).alias("n_ptns_total"),

        (pl.col("Source") == "Virus").sum().cast(pl.Int32).alias("n_viral_ptns"),
        (pl.col("Source") == "Host").sum().cast(pl.Int32).alias("n_host_ptns"),
        (pl.col("Source") == "MGE").sum().cast(pl.Int32).alias("n_mge_ptns"),

        (pl.col("True Positive") == True).sum().cast(pl.Int32).alias("n_true_viral"),

        pl.col("_relabeled").sum().cast(pl.Int32).alias("n_ptns_relabeled"),
        pl.col("_in_strict_viral_region").sum().cast(pl.Int32).alias("n_ptns_strict_viral_region"),
    ])
    .with_columns([
        (pl.col("n_viral_ptns") / pl.col("n_ptns_total")).cast(pl.Float32).alias("pct_source_viral_ptns"),
        (pl.col("n_host_ptns") / pl.col("n_ptns_total")).cast(pl.Float32).alias("pct_source_host_ptns"),
        (pl.col("n_mge_ptns") / pl.col("n_ptns_total")).cast(pl.Float32).alias("pct_source_mge_ptns"),
        (pl.col("n_true_viral") / pl.col("n_ptns_total")).cast(pl.Float32).alias("pct_true_viral"),
        (pl.col("n_ptns_relabeled") / pl.col("n_ptns_total")).cast(pl.Float32).alias("pct_ptns_relabeled"),
        (pl.col("n_ptns_strict_viral_region") / pl.col("n_ptns_total")).cast(pl.Float32).alias("pct_ptns_strict_viral_region"),
    ])
    .rename({"Dataset": "dataset"})
    .sort(["dataset", "contig"])
)

In [286]:
sequence_table

shape: (226_631, 18)
┌────────────┬───────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ contig     ┆ dataset   ┆ region_co ┆ length  ┆ … ┆ pct_sourc ┆ pct_true_ ┆ pct_ptns_ ┆ pct_ptns_ │
│ ---        ┆ ---       ┆ ntig_type ┆ ---     ┆   ┆ e_mge_ptn ┆ viral     ┆ relabeled ┆ strict_vi │
│ str        ┆ str       ┆ ---       ┆ i32     ┆   ┆ s         ┆ ---       ┆ ---       ┆ ral_regio │
│            ┆           ┆ str       ┆         ┆   ┆ ---       ┆ f32       ┆ f32       ┆ n         │
│            ┆           ┆           ┆         ┆   ┆ f32       ┆           ┆           ┆ ---       │
│            ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆ f32       │
╞════════════╪═══════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1039479_co ┆ geNomad   ┆ standalon ┆ 4199    ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 0.0       │
│ ntig_5232_ ┆           ┆ e_virus   ┆         ┆   ┆           ┆           ┆           ┆           │
│ 3_1039479_ ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ contig_523 ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 2|fragment ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ _1         ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1085434_co ┆ geNomad   ┆ standalon ┆ 3906    ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 0.0       │
│ ntig_2176_ ┆           ┆ e_virus   ┆         ┆   ┆           ┆           ┆           ┆           │
│ 7_1085434_ ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ contig_217 ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 6|fragment ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ _1         ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1085436_co ┆ geNomad   ┆ standalon ┆ 6590    ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 0.545455  │
│ ntig_405_6 ┆           ┆ e_virus   ┆         ┆   ┆           ┆           ┆           ┆           │
│ _1085436_c ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ ontig_405| ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ fragment_1 ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1093096_co ┆ geNomad   ┆ standalon ┆ 3153    ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 0.0       │
│ ntig_1717_ ┆           ┆ e_virus   ┆         ┆   ┆           ┆           ┆           ┆           │
│ 4_1093096_ ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ contig_171 ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 7|fragment ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ _1         ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 10H_2_1994 ┆ geNomad   ┆ standalon ┆ 5340    ┆ … ┆ 0.0       ┆ 1.0       ┆ 0.0       ┆ 0.0       │
│ 0_cov_32_0 ┆           ┆ e_virus   ┆         ┆   ┆           ┆           ┆           ┆           │
│ |fragment_ ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 1          ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …         ┆ …         ┆ …       ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 999541.SAM ┆ progenome ┆ chromosom ┆ 4413285 ┆ … ┆ 0.197839  ┆ 0.07152   ┆ 0.348341  ┆ 0.126833  │
│ N02603164. ┆ s         ┆ e_mixed   ┆         ┆   ┆           ┆           ┆           ┆           │
│ CP002599~1 ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ -4413616~c ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ hromosome_ ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ mixed      ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 999541.SAM ┆ progenome ┆ chromosom ┆ 3700565 ┆ … ┆ 0.303618  ┆ 0.003876  ┆ 0.321382  ┆ 0.031331  │
│ N02603164. ┆ s         ┆ e_mixed   ┆         ┆   ┆           ┆           ┆           ┆           │
│ CP002600~1 ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ -3700833~c ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ hromosome_ ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ mixed      ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 999543.SAM ┆ progenome ┆ chromosom ┆ 59196   ┆ … ┆ 0.985507  ┆ 0.0       ┆ 0.0       ┆ 0.753623  │
│ N02261279. ┆ s         ┆ e_mixed   ┆         ┆   ┆           ┆           ┆           ┆           │
│ KB905360~1 ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ -59197~chr ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ omosome_mi ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ xed        ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 999543.SAM ┆ progenome ┆ chromosom ┆ 34130   ┆ … ┆ 0.0       ┆ 0.877551  ┆ 0.122449  ┆ 0.877551  │
│ N02261279. ┆ s         ┆ e_mixed   ┆         ┆   ┆           ┆           ┆           ┆           │
│ KB905361~1 ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ -34131~chr ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ omosome_mi ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ xed        ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 999547.SAM ┆ progenome ┆ chromosom ┆ 3984463 ┆ … ┆ 0.069805  ┆ 0.0       ┆ 0.0       ┆ 0.069805  │
│ N02440716. ┆ s         ┆ e_mixed   ┆         ┆   ┆           ┆           ┆           ┆           │
│ KI421500~1 ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ -3984464~c ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ hromosome_ ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ mixed      ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
└────────────┴───────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [289]:
sequence_table.write_parquet(OUTPUT_TABLES_DIR.joinpath("genes_sequence_table.parquet"))